# Generated by Django 5.2.6 on 2025-11-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('symptoms', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('city_of_practice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNKNOWN')], default='U', max_length=1)),
                ('city_of_residence', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cancer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('current_status', models.CharField(choices=[('I', 'INCOMPLETE'), ('C', 'COMPLETE CURE'), ('P', 'PARTIAL CURE')], default='I', max_length=1)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.diagnosis')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_doctor_patient')],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('patient', 'cancer'), name='unique_cancer_patient'),
        ),
        migrations.AddConstraint(
            model_name='treats',
            constraint=models.UniqueConstraint(fields=('diagnosis', 'treatment'), name='unique_diagnosis_treatment'),
        ),
    ]
