# Generated by Django 5.2.6 on 2025-11-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evaluates',
            new_name='Evaluate',
        ),
        migrations.RenameModel(
            old_name='Treats',
            new_name='Treat',
        ),
    ]
