# Generated by Django 5.2.6 on 2025-11-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_evaluates_evaluate_rename_treats_treat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treat',
            new_name='CancerTreatment',
        ),
    ]
